### ISSUE TITLE
validators being run even if error is raised

### ISSUE THREAD

**Issue by bmeyer71** [zerok/django-validatorchain#1]
Given the age of this repo, I'm not sure if it is still valid or supported, but thought I would open a ticket and see. :)

I am using Django 2.2.x and Python 3.7
For some reason, even if I set a validator to skip_on_error it is still being run.
It's as though the `if next_item.skip_on_error and self._has_error:` never equals True for both.

During my tests, that section gets run in init, but never seems to be run as part of the function it returns.

Any help is appreciated.
Thank you.

**Comment by zerok** [comment]
Sorry for taking so long to respond :( I will try to look into it this week :)

**Comment by zerok** [comment]
Meh, looks like in Django now copies the validators out of the `self.validators` during the Field's initialization :( https://github.com/django/django/blob/92309e53d9921a60e667656d8dd65e59eb5cf81c/django/forms/fields.py#L116

This means that the iterator is only run during initialization and not when the validation actually happens. So, I guess, I can archive this project now 🤣

Sorry 😞
